### ISSUE TITLE
Bundled SFZero module is old

### ISSUE THREAD

**Issue by KottV** [osxmidi/SFZero-X#1]
Hi,

I'm trying to compile this new source and found that plugin/JuceLibraryCode/modules/SFZero contains old version. I thought that yours SFZero-X-Module is required.

**Comment by osxmidi** [comment]
I've rearranged it.

The SFZero module is the SFZero-X module.

For Juce 5 copy the files in SFZero-X/plugin/JuceLibraryCode/modules/SFZero/sfzero/Juce5 to 
SFZero-X/plugin/JuceLibraryCode/modules/SFZero/sfzero

**Comment by KottV** [comment]
Thanks!
