### ISSUE TITLE
JUCE LV2 links

### ISSUE THREAD

**Issue by KottV** [osxmidi/SFZero-X#2]
Hi!

I have to mention that LV2 version of JUCE is in separate branch https://github.com/lv2-porting-project/JUCE/tree/lv2

**Comment by osxmidi** [comment]
> Hi!
> 
> I have to mention that LV2 version of JUCE is in separate branch https://github.com/lv2-porting-project/JUCE/tree/lv2

Thanks.

I've updated the Readme.

**Comment by KottV** [comment]
thnx!
