### ISSUE TITLE
xfout_locc xfout_hicc

### ISSUE THREAD

**Issue by akinoruto** [osxmidi/SFZero-X#3]
Region does not play
on xfout_locc xfout_hicc setting.

usage environment
linuxmint19.3
REAPER6.13
Binary vst3 sfzero-X
I love sfzero-X. I want you to fix it

**Comment by osxmidi** [comment]
> Region does not play
> on xfout_locc xfout_hicc setting.
> 
> usage environment
> linuxmint19.3
> REAPER6.13
> Binary vst3 sfzero-X
> I love sfzero-X. I want you to fix it

I tested the sfz file below with SFXero-X and Sforzando and they both seem to produce the same results when using the mod wheel (cc1).

<control>
default_path=./
<global>ampeg_release=0.3 amp_veltrack=0

<group>lokey=50 hikey=51 pitch_keycenter=50
<region>sample=riser_02.wav xfin_locc1=0 xfin_hicc1=42 xfout_locc1=43 xfout_hicc1=85
<region>sample=riser_06.wav xfin_locc1=43 xfin_hicc1=85 xfout_locc1=86 xfout_hicc1=127
<region>sample=riser_07.wav xfin_locc1=86 xfin_hicc1=127
<group>lokey=52 hikey=53 pitch_keycenter=52
<region>sample=riser_08.wav xfin_locc1=0 xfin_hicc1=42 xfout_locc1=43 xfout_hicc1=85
<region>sample=riser_09.wav xfin_locc1=43 xfin_hicc1=85 xfout_locc1=86 xfout_hicc1=127
<region>sample=riser_10.wav xfin_locc1=86 xfin_hicc1=127

**Comment by akinoruto** [comment]
it was necessary to describe xfin_cc as a set even when only fading out.

It moved safely.
thank you.
